import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db/client';
import { requireSession, ForbiddenError } from '@/lib/auth/session';
import { withErrorHandling } from '@/lib/api/respond';
import { audit } from '@/lib/audit/log';
import { canReviewWorkspace } from '@/lib/permissions/reviewer';
import { renderFromSnapshot } from '@/lib/documents/campaign';
import { contentDisposition } from '@/lib/documents/http';
import { DocumentFileError } from '@/lib/documents/inspect';
import { DocumentRenderError } from '@/lib/documents/render';
import { parseSnapshot } from '@/lib/documents/types';
import { Role } from '@prisma/client';

export const maxDuration = 30;

/**
 * Downloads the personalised PDF sent with a campaign email.
 *
 * MailFlow does not store generated bytes; it regenerates the copy from the
 * frozen snapshot (same PDF, same values, same reference and date) and
 * compares its SHA-256 with the hash recorded at send time.
 * `?verify=1` returns just that comparison; `?inline=1` opens in the browser.
 */
export const GET = withErrorHandling(async (req, { params }: { params: { id: string } }) => {
  const session = await requireSession();
  const attachment = await prisma.attachment.findUnique({
    where: { id: params.id },
    include: {
      campaignDocument: { select: { name: true, fileId: true, fields: true, lockMode: true, stampReference: true } },
      emailJob: { select: { status: true, toEmail: true, campaign: { select: { workspaceId: true } } } },
      conversationMessage: { select: { conversation: { select: { workspaceId: true } } } },
    },
  });
  if (!attachment) return NextResponse.json({ error: 'Not found' }, { status: 404 });

  const workspaceId = attachment.emailJob?.campaign.workspaceId ?? attachment.conversationMessage?.conversation.workspaceId ?? null;
  if (!workspaceId) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  if (workspaceId !== session.workspaceId && session.role !== Role.SUPER_ADMIN && !(await canReviewWorkspace(session, workspaceId))) {
    throw new ForbiddenError('Not your workspace');
  }

  if (!attachment.campaignDocumentId || !attachment.campaignDocument) {
    return NextResponse.json(
      { error: 'MailFlow does not keep a copy of this attachment. Open the email in Gmail to download it.' },
      { status: 404 }
    );
  }
  const snapshot = parseSnapshot(attachment.fieldValues);
  if (!snapshot) return NextResponse.json({ error: 'The saved values for this document could not be read.' }, { status: 422 });

  let rendered;
  try {
    rendered = await renderFromSnapshot(attachment.campaignDocument, snapshot);
  } catch (err) {
    if (err instanceof DocumentRenderError || err instanceof DocumentFileError) {
      return NextResponse.json({ error: err.message }, { status: 422 });
    }
    throw err;
  }

  const verification = !attachment.sha256 ? 'not-sent-yet' : attachment.sha256 === rendered.sha256 ? 'identical' : 'differs';
  const url = new URL(req.url);

  if (url.searchParams.get('verify') === '1') {
    return NextResponse.json({
      verification,
      filename: attachment.filename,
      reference: attachment.documentRef,
      recipient: attachment.emailJob?.toEmail ?? snapshot.recipient,
      sentSha256: attachment.sha256,
      regeneratedSha256: rendered.sha256,
      generatedAt: attachment.generatedAt,
      size: rendered.bytes.length,
    });
  }

  await audit(session, 'DOCUMENT_DOWNLOAD', {
    targetType: 'Attachment',
    targetId: attachment.id,
    metadata: { reference: attachment.documentRef, verification },
  });

  return new NextResponse(new Uint8Array(rendered.bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': contentDisposition(url.searchParams.get('inline') === '1' ? 'inline' : 'attachment', attachment.filename),
      'Cache-Control': 'private, no-store',
      'X-Content-Type-Options': 'nosniff',
      'X-MailFlow-Sha256': rendered.sha256,
      'X-MailFlow-Verification': verification,
    },
  });
});
